// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"tmail/ent/attachment"
	"tmail/ent/envelope"
	"tmail/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttachmentUpdate is the builder for updating Attachment entities.
type AttachmentUpdate struct {
	config
	hooks    []Hook
	mutation *AttachmentMutation
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (au *AttachmentUpdate) Where(ps ...predicate.Attachment) *AttachmentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetFilename sets the "filename" field.
func (au *AttachmentUpdate) SetFilename(s string) *AttachmentUpdate {
	au.mutation.SetFilename(s)
	return au
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (au *AttachmentUpdate) SetNillableFilename(s *string) *AttachmentUpdate {
	if s != nil {
		au.SetFilename(*s)
	}
	return au
}

// SetFilepath sets the "filepath" field.
func (au *AttachmentUpdate) SetFilepath(s string) *AttachmentUpdate {
	au.mutation.SetFilepath(s)
	return au
}

// SetNillableFilepath sets the "filepath" field if the given value is not nil.
func (au *AttachmentUpdate) SetNillableFilepath(s *string) *AttachmentUpdate {
	if s != nil {
		au.SetFilepath(*s)
	}
	return au
}

// SetContentType sets the "contentType" field.
func (au *AttachmentUpdate) SetContentType(s string) *AttachmentUpdate {
	au.mutation.SetContentType(s)
	return au
}

// SetNillableContentType sets the "contentType" field if the given value is not nil.
func (au *AttachmentUpdate) SetNillableContentType(s *string) *AttachmentUpdate {
	if s != nil {
		au.SetContentType(*s)
	}
	return au
}

// SetOwnerID sets the "owner" edge to the Envelope entity by ID.
func (au *AttachmentUpdate) SetOwnerID(id int) *AttachmentUpdate {
	au.mutation.SetOwnerID(id)
	return au
}

// SetNillableOwnerID sets the "owner" edge to the Envelope entity by ID if the given value is not nil.
func (au *AttachmentUpdate) SetNillableOwnerID(id *int) *AttachmentUpdate {
	if id != nil {
		au = au.SetOwnerID(*id)
	}
	return au
}

// SetOwner sets the "owner" edge to the Envelope entity.
func (au *AttachmentUpdate) SetOwner(e *Envelope) *AttachmentUpdate {
	return au.SetOwnerID(e.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (au *AttachmentUpdate) Mutation() *AttachmentMutation {
	return au.mutation
}

// ClearOwner clears the "owner" edge to the Envelope entity.
func (au *AttachmentUpdate) ClearOwner() *AttachmentUpdate {
	au.mutation.ClearOwner()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AttachmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AttachmentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AttachmentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AttachmentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AttachmentUpdate) check() error {
	if v, ok := au.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if v, ok := au.mutation.Filepath(); ok {
		if err := attachment.FilepathValidator(v); err != nil {
			return &ValidationError{Name: "filepath", err: fmt.Errorf(`ent: validator failed for field "Attachment.filepath": %w`, err)}
		}
	}
	if v, ok := au.mutation.ContentType(); ok {
		if err := attachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "contentType", err: fmt.Errorf(`ent: validator failed for field "Attachment.contentType": %w`, err)}
		}
	}
	return nil
}

func (au *AttachmentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := au.mutation.Filepath(); ok {
		_spec.SetField(attachment.FieldFilepath, field.TypeString, value)
	}
	if value, ok := au.mutation.ContentType(); ok {
		_spec.SetField(attachment.FieldContentType, field.TypeString, value)
	}
	if au.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AttachmentUpdateOne is the builder for updating a single Attachment entity.
type AttachmentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttachmentMutation
}

// SetFilename sets the "filename" field.
func (auo *AttachmentUpdateOne) SetFilename(s string) *AttachmentUpdateOne {
	auo.mutation.SetFilename(s)
	return auo
}

// SetNillableFilename sets the "filename" field if the given value is not nil.
func (auo *AttachmentUpdateOne) SetNillableFilename(s *string) *AttachmentUpdateOne {
	if s != nil {
		auo.SetFilename(*s)
	}
	return auo
}

// SetFilepath sets the "filepath" field.
func (auo *AttachmentUpdateOne) SetFilepath(s string) *AttachmentUpdateOne {
	auo.mutation.SetFilepath(s)
	return auo
}

// SetNillableFilepath sets the "filepath" field if the given value is not nil.
func (auo *AttachmentUpdateOne) SetNillableFilepath(s *string) *AttachmentUpdateOne {
	if s != nil {
		auo.SetFilepath(*s)
	}
	return auo
}

// SetContentType sets the "contentType" field.
func (auo *AttachmentUpdateOne) SetContentType(s string) *AttachmentUpdateOne {
	auo.mutation.SetContentType(s)
	return auo
}

// SetNillableContentType sets the "contentType" field if the given value is not nil.
func (auo *AttachmentUpdateOne) SetNillableContentType(s *string) *AttachmentUpdateOne {
	if s != nil {
		auo.SetContentType(*s)
	}
	return auo
}

// SetOwnerID sets the "owner" edge to the Envelope entity by ID.
func (auo *AttachmentUpdateOne) SetOwnerID(id int) *AttachmentUpdateOne {
	auo.mutation.SetOwnerID(id)
	return auo
}

// SetNillableOwnerID sets the "owner" edge to the Envelope entity by ID if the given value is not nil.
func (auo *AttachmentUpdateOne) SetNillableOwnerID(id *int) *AttachmentUpdateOne {
	if id != nil {
		auo = auo.SetOwnerID(*id)
	}
	return auo
}

// SetOwner sets the "owner" edge to the Envelope entity.
func (auo *AttachmentUpdateOne) SetOwner(e *Envelope) *AttachmentUpdateOne {
	return auo.SetOwnerID(e.ID)
}

// Mutation returns the AttachmentMutation object of the builder.
func (auo *AttachmentUpdateOne) Mutation() *AttachmentMutation {
	return auo.mutation
}

// ClearOwner clears the "owner" edge to the Envelope entity.
func (auo *AttachmentUpdateOne) ClearOwner() *AttachmentUpdateOne {
	auo.mutation.ClearOwner()
	return auo
}

// Where appends a list predicates to the AttachmentUpdate builder.
func (auo *AttachmentUpdateOne) Where(ps ...predicate.Attachment) *AttachmentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AttachmentUpdateOne) Select(field string, fields ...string) *AttachmentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Attachment entity.
func (auo *AttachmentUpdateOne) Save(ctx context.Context) (*Attachment, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AttachmentUpdateOne) SaveX(ctx context.Context) *Attachment {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AttachmentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AttachmentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AttachmentUpdateOne) check() error {
	if v, ok := auo.mutation.Filename(); ok {
		if err := attachment.FilenameValidator(v); err != nil {
			return &ValidationError{Name: "filename", err: fmt.Errorf(`ent: validator failed for field "Attachment.filename": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Filepath(); ok {
		if err := attachment.FilepathValidator(v); err != nil {
			return &ValidationError{Name: "filepath", err: fmt.Errorf(`ent: validator failed for field "Attachment.filepath": %w`, err)}
		}
	}
	if v, ok := auo.mutation.ContentType(); ok {
		if err := attachment.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "contentType", err: fmt.Errorf(`ent: validator failed for field "Attachment.contentType": %w`, err)}
		}
	}
	return nil
}

func (auo *AttachmentUpdateOne) sqlSave(ctx context.Context) (_node *Attachment, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attachment.Table, attachment.Columns, sqlgraph.NewFieldSpec(attachment.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Attachment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attachment.FieldID)
		for _, f := range fields {
			if !attachment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attachment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Filename(); ok {
		_spec.SetField(attachment.FieldFilename, field.TypeString, value)
	}
	if value, ok := auo.mutation.Filepath(); ok {
		_spec.SetField(attachment.FieldFilepath, field.TypeString, value)
	}
	if value, ok := auo.mutation.ContentType(); ok {
		_spec.SetField(attachment.FieldContentType, field.TypeString, value)
	}
	if auo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   attachment.OwnerTable,
			Columns: []string{attachment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envelope.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Attachment{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attachment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
