// Code generated by ent, DO NOT EDIT.

package attachment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the attachment type in the database.
	Label = "attachment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldFilepath holds the string denoting the filepath field in the database.
	FieldFilepath = "filepath"
	// FieldContentType holds the string denoting the contenttype field in the database.
	FieldContentType = "content_type"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the attachment in the database.
	Table = "attachments"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "attachments"
	// OwnerInverseTable is the table name for the Envelope entity.
	// It exists in this package in order to avoid circular dependency with the "envelope" package.
	OwnerInverseTable = "envelopes"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "envelope_attachments"
)

// Columns holds all SQL columns for attachment fields.
var Columns = []string{
	FieldID,
	FieldFilename,
	FieldFilepath,
	FieldContentType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attachments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"envelope_attachments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
	// FilepathValidator is a validator for the "filepath" field. It is called by the builders before save.
	FilepathValidator func(string) error
	// ContentTypeValidator is a validator for the "contentType" field. It is called by the builders before save.
	ContentTypeValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Attachment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// ByFilepath orders the results by the filepath field.
func ByFilepath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilepath, opts...).ToFunc()
}

// ByContentType orders the results by the contentType field.
func ByContentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentType, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
