// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Envelope is the predicate function for envelope builders.
type Envelope func(*sql.Selector)
